### ISSUE TITLE
Update ptegu and ptnoipm sectors to use same UTM for all sources within the same facility

### ISSUE THREAD

**Issue by bokhaeng** [CEMPD/SMOKE#10]
UTM needs to be the same for all sources within the same facility for ptegu and ptnoipm sectors

**Comment by cseppan** [comment]
Commit 3093121 adds logic to the individual ptnonipm & ptegu scripts to use the same UTM zone for all sources at a facility. Still need to create a script to combine the two sectors.

**Comment by cseppan** [comment]
Commit 3b6a8ce11fd6ee3ddde3d9436a1c08450f875acb adds a script to combine the ptegu & ptnonipm outputs. For the location files, the script ensures that AERMOD sources at the same facility use the same UTM zone and grid cell, based on the ptegu sector values.
