### ISSUE TITLE
miscalculated hourly emissions with SMOKE 5.1

### ISSUE THREAD

**Issue by callen52** [CEMPD/SMOKE#100]
[cmv_c3_hourly_test_case_for_github_10jul2024.zip](https://github.com/user-attachments/files/16164783/cmv_c3_hourly_test_case_for_github_10jul2024.zip)

For CMV sectors, we use hourly FF10 inventories. In SMOKE 5.1, I am finding that the hourly emissions are occasionally being miscalculated, often in the first hour of the day. This was not a problem with SMOKE 5.0.

The attachment contains:
- sample annual (*annual*csv*) and hourly (*hourly*csv*) inventories, intended to be run through SMOKE for the month of March
- sample run scripts (onetime and daily)
- hourly Smkreports for one example day when using SMOKE 5.0 (rep*smk50*) versus SMOKE 5.1 (rep*smk51*). If you do a diff on the two reports, you'll see where the smk51 emissions are higher. I've confirmed that the smk50 emissions match the hourly inventory and are correct.

**Comment by hnqtran** [comment]
Hi @callen52, I don't think I have all inputs to replicate the runs. I believe there're at least temporal profiles and repconfig files are missing.

**Comment by callen52** [comment]
You can use the temporal profiles/xrefs from 2021 platform for this test (none of the changes in 2022 platform impact CMV): https://gaftp.epa.gov/air/emismod/2021/ancillary_data/temporal_ge_dat_2021hb_17jun2024.zip

Here is the REPCONFIG I used to generate the hourly Smkreports that illustrate the issue:
[REPCONFIG_for_cmv_bug.txt](https://github.com/user-attachments/files/16272787/REPCONFIG_for_cmv_bug.txt)

**Comment by hnqtran** [comment]
This issue was found to related to issue #91. Fix implemented for ptagfire test case in issue #91 also fixed the issue for cmv_c3 test case in this issue.

@callen52, would you be able to compile the latest SMOKE github version and let me know if all issues #91, #97 and #100 are fixed on your end? Thanks.
