### ISSUE TITLE
provide additional "How to Use SMOKE" documentation

### ISSUE THREAD

**Issue by cseppan** [CEMPD/SMOKE#56]
As part of the SMOKE v4.9 release, chapters specific to the old Assigns file and run scripts were removed from the SMOKE User's Guide ([v4.9 guide](https://cmascenter.org/smoke/documentation/4.9/html/)). This how-to guidance needs to be updated based on the Emissions Modeling Platform scripts and made available to users, possibly on the SMOKE GitHub site or through the CMAS wiki.

old chapters from the SMOKE v4.8.1 User's Guide
[SMOKE Directory Structure](https://cmascenter.org/smoke/documentation/4.8.1/html/ch03.html)
[How to Use SMOKE](https://cmascenter.org/smoke/documentation/4.8.1/html/ch04.html)
[Source Code and Include Files](https://cmascenter.org/smoke/documentation/4.8.1/html/ch11.html)
[Downloading, Installing, and Compiling SMOKE](https://cmascenter.org/smoke/documentation/4.8.1/html/ch12.html)

The CMAS wiki has a page detailing the 2011v6.3 package:
https://www.airqualitymodeling.org/index.php/SMOKE-NEI-Platform6.3

Each platform provides similar information in a text file:
[2016v1](https://gaftp.epa.gov/air/emismod/2016/v1/2016_v1_platform_package_info_30apr2021.txt)
[2016v2](https://gaftp.epa.gov/air/emismod/2016/v2/2016_v2_platform_package_info.txt)
[2017](https://gaftp.epa.gov/air/emismod/2017/2017gb_package_12jul2021_info.txt)

**Comment by cseppan** [comment]
Revised the main SMOKE page on the CMAS wiki: https://www.airqualitymodeling.org/index.php/SMOKE

Added pages for

2016v2: https://www.airqualitymodeling.org/index.php/2016v2_Emissions_Modeling_Platform
2017: https://www.airqualitymodeling.org/index.php/2017_Emissions_Modeling_Platform

**Comment by christos-e** [comment]
Sections 12.2 and 12.3 can be simply replaced by the git clone command of the SMOKE repo. 

The previous information in section 12.4 is still relevant on RHEL8 standard Linux distributions with respect to installing IOAPI. 
Note that some Linux variants do not use the same standards and that possibly confuse users (i.e. Debian). 

Once the user has the IOAPI and SMOKE repo setup, the Makeinclude file ind the src directory needs to be modified according to the user's SMK_HOME, BIN, IOBASE, INSTDIR.

From Architecture perspective the user needs to specify compiler-specific choices which may require additional flags for specific hardware. 

Regarding netcdf-4 the user may need to include NFDIR and NCDIR library paths explicitly: i.e:

 IOLIB = -L$(IOBIN) -lioapi -L${NFDIR}/lib -lnetcdff -L${NCDIR}/lib -lnetcdf

The next step would be to proceed with issuing the Make command, and verify the compiled objects can be found in INSTDIR.

**Comment by cseppan** [comment]
GitHub wiki pages that are linked from the CMAS Center SMOKE site

[SMOKE Compilation Instructions](https://github.com/CEMPD/SMOKE/wiki)
[Running SMOKE using EPA's Emissions Modeling Platforms](https://github.com/CEMPD/SMOKE/wiki/Running-SMOKE-using-EPA's-Emissions-Modeling-Platforms)
