### ISSUE TITLE
update documentation link printed in SMOKE logs

### ISSUE THREAD

**Issue by cseppan** [CEMPD/SMOKE#59]
lib/initem.f writes out various information at the start of each program. Currently the online documentation link is an old URL that doesn't exist anymore (http://www.cep.unc.edu/empd/products/smoke). Update to https://cmascenter.org/smoke/

**Comment by bokhaeng** [comment]
@cseppan  FYI, I accidentally committed this change to the SMOKE-MetEmis branch. It should be ok once they are merged later.
