### ISSUE TITLE
Update Lat/Lon in point helper location files need to be exactly the same as what is in the FF10

### ISSUE THREAD

**Issue by bokhaeng** [CEMPD/SMOKE#6]
Update Lat/Lon in point helper location files need to be exactly the same as what is in the FF10 and the UTM should be based on that (UNC: 1/12/2017): Done (CSRA)

**Comment by cseppan** [comment]
Not sure anything needs to be done here apart from issue #16

**Comment by bokhaeng** [comment]
Completed. No work is needed.
