### ISSUE TITLE
add SMK_ELEV_METHOD and INLN files to Smkmerge documentation

### ISSUE THREAD

**Issue by cseppan** [CEMPD/SMOKE#63]
https://cmascenter.org/smoke/documentation/4.9/html/ch04s15s03.html

Need to include SMK_ELEV_METHOD in the Input Environment Variables section. Like the existing SMK_PING_METHOD, this can link to the relevant Elevpoint section.

Add INLN[T][S][_S|_L] to Output Files table

Can look at updating the figure "Smkmerge input and output files for point sources"
https://cmascenter.org/smoke/documentation/4.9/html/ch04s15s03.html#fig_programs_smkmerge_point

**Comment by bokhaeng** [comment]
The Smkmerge section has been updated with SMK_ELEV_METHOD and INLN[T][S][_S|_L] to output Files table.
Updated the Smkmerge Point figure with [T][S][_S|_L] when SMK_ELEV_METHOD=2
