### ISSUE TITLE
Using SMOKE for domains outside US

### ISSUE THREAD

**Issue by ramespada** [CEMPD/SMOKE#67]
Hi!

I wondering if it is possible to use SMOKE to prepare anthropogenic emissions from ascii files (using a similar format that NEIs inventories for example) on domains outside US.  

I have read in the documentation that these kind of files includes codes/flags related to the country, but only US, Mexico and Canada are considered. So I want to know if it worth to me to learn this tools, thanks!

**Comment by bokhaeng** [comment]
Please submit any operational related questions through CMAS forum website (forum.cmascenter.org)
