### ISSUE TITLE
remove obsolete BlueSky2Inv from release

### ISSUE THREAD

**Issue by cseppan** [CEMPD/SMOKE#74]
Remove from documentation:

https://cmascenter.org/smoke/documentation/4.9/html/ch03s03.html
https://cmascenter.org/smoke/documentation/4.9/html/ch03s03s03.html

Remove code from repository: emutil/bluesky2inv.f
Update Makefile to not look for the file or try to create the executable

**Comment by bokhaeng** [comment]
Updated Chapters 1 and 3 to remove the Bluesky2Inv interface tool from the manual.

**Comment by bokhaeng** [comment]
@cseppan Do you want me to remove the bluesky2inv.f code and update Makefile from SMOKE repo?
