### ISSUE TITLE
Assign all ptnonipm & ptegu sources at the same facility to the same grid cell

### ISSUE THREAD

**Issue by bokhaeng** [CEMPD/SMOKE#8]

**Comment by cseppan** [comment]
Commit 3093121 adds logic to the individual ptnonipm & ptegu scripts set set the grid cell for a facility based on the maximum emissions. Still need to create a script to combine the two sectors.

**Comment by cseppan** [comment]
Commit 3b6a8ce11fd6ee3ddde3d9436a1c08450f875acb adds a script to combine the ptegu & ptnonipm outputs. For the location files, the script ensures that AERMOD sources at the same facility use the same UTM zone and grid cell, based on the ptegu sector values.
