### ISSUE TITLE
review potential updates to Tmpbeis4 code

### ISSUE THREAD

**Issue by cseppan** [CEMPD/SMOKE#84]
Based on October 29, 2023 email from Carlie Coats

Draft code (has not been compiled or tested). Switch to using M3UTILIO module in Tmpbeis4. Change grid-and-species loop nests. Check for failure after environment variable calls (e.g. ENVINT).

"tmpbeis4.0.f"  is the un-changed reference version
"tmpbeis4.1.f" is the minimal changes-for-M3UTILIO version
"tmpbeis4.2.f" with loop-nest orders changed for efficiency
"tmpbeis4.f" further revision sent

[tmpbeis.zip](https://github.com/CEMPD/SMOKE/files/13311257/tmpbeis.zip)

**Comment by cseppan** [comment]
Discussion of the I/O API M3UTILIO module and how to convert existing code
https://cmascenter.org/ioapi/documentation/all_versions/html/M3UTILIO.html

**Comment by hnqtran** [comment]
Summary of Carlie's updates to tmpbeis4.f:

* Reconcile ALLOCATE statements. For example, lines 793 - 805 in original tmpbeis4.f
```
        IF( PX_VERSION ) THEN
            ALLOCATE( SOILM( NCOLS, NROWS ), STAT=IOS )
            CALL CHECKMEM( IOS, 'SOILM', PROGNAME )

            ALLOCATE( SOILT( NCOLS, NROWS ), STAT=IOS )
            CALL CHECKMEM( IOS, 'SOILT', PROGNAME )

            ALLOCATE( SOILT2( NCOLS, NROWS ), STAT=IOS )
            CALL CHECKMEM( IOS, 'SOILT2', PROGNAME )

            ALLOCATE( ISLTYP( NCOLS, NROWS ), STAT=IOS )
            CALL CHECKMEM( IOS, 'ISLTYP', PROGNAME )
        END IF
```
was modified to (lines 524 - 528 in updated tmpbeis4.f):
```
 IF (PX_VERSION) THEN ! line 480
....
            ALLOCATE( SOILM( NCOLS, NROWS ),
     &                SOILT( NCOLS, NROWS ),
     &               SOILT2( NCOLS, NROWS ),
     &               ISLTYP( NCOLS, NROWS ), STAT=IOS )
            CALL CHECKMEM( IOS, 'SOILM...ISLTYP', PROGNAME )
```

* Re-arrange loop structure for better execution efficiency. For example, lines 1030 in original tmpbeis4.f:
```
                    DO I = 1, NCOLS
                        DO J = 1, NROWS

C.............................  If switch equal to 0 use winter normalized emissions
                          IF( SWITCH_FILE ) THEN
                            IF( SWITCH( I,J ) == 0 ) THEN
                                SEMIS( I, J, 1:NSEF   ) =
     &                              AVGEMIS( I, J, 1:NSEF  , NWINTER )
                                     .........
```
was modified to (~ line 1048 in updated tmpbeis4.f. Note how I and J loop was switched):
```
                        DO J = 1, NROWS
                        DO I = 1, NCOLS

                            IF( SWITCH( I,J ) == 0 ) THEN
                                SEMIS( I, J, 1:NSEF   ) =
     &                              AVGEMIS( I, J, 1:NSEF  , NWINTER )
                                     .........
```

* Carlie add a code block for unit conversion from mole/hr to mole/s (~ lines 1001 - 1010 in updated tmpbeis4.f). It is, however, unclear if this unit conversion was taken care of elsewhere outside tmpbeis4 (if it was not, then this has serious implication on emission output)
```
C............  Convert to moles/second if necessary

        IF ( UNITTYPE .EQ. 2 ) THEN
            DO L = 1, MSPCS
            DO K = 1, NSEF
                MLFAC( L, K ) = HR2SEC * MLFAC( L, K )
            END DO
            END DO
        END IF
```

**Comment by hnqtran** [comment]
Testing of tmpbeis4 with and without update, surprisingly, did not show improvement in the execution time. Note that the test was conducted on a SMOKE training package over LISTOS domain (25 row x 25 col). Observable improvement in execution time could be expected for larger domain.

Using m3diff tool to compare emis_mole* output files initially showed significantly lower emissions in the output files with updated tmpbeis4. This was later found to be caused by the double unit conversion in the updated tmpbeis4 (item 5 in comment above). After this double unit conversion was removed, differences between the outputs are < 0.1% which are in acceptable range.

**Comment by eyth** [comment]
Huy, can you consider running this on the full 12US2 or 12US1 domain
instead of the 25x25?

**Comment by hnqtran** [comment]
> Huy, can you consider running this on the full 12US2 or 12US1 domain instead of the 25x25?
> […](#)

I'm working on setting up test case based on emission platform 2020ha2 for 12US1 domain. Currently having issue with missing variable SOILT2 in the input met file METCRO2D.
