### ISSUE TITLE
make SPEED inventory optional

### ISSUE THREAD

**Issue by cseppan** [CEMPD/SMOKE#86]
> SMOKE will crash if we leave the SPEED inventory out of the run. Otherwise, we would be able to drop it altogether. In 2020 platform, we are using a dummy SPEED inventory that just covers one county.
>  
> We may want to add this to the list of possible SMOKE enhancements… 1) remove the requirement for a SPEED dataset if we have a SPDIST (or the older SPDPRO), and 2) have Movesmrg return an error if the SPDIST is missing data for any county/SCC/month (I don’t remember if we even get a warning about this currently).

**Comment by bokhaeng** [comment]
Updated Movesmrg to treat SPEED inventory as optional. The SPEED is no longer a mandatory input. VMT along can be processed along with either SPDIST or SPDPRO input files. 

Also added error messages when the SPDIST or SPDPRO is missing for any county/scc/month entry.

https://github.com/CEMPD/SMOKE/commit/6b8c9adb48877d3284cbfba97c4f204942f5181c

**Comment by hnqtran** [comment]
Tested and confirm that SPEED inventory is not required for processing onroad RPD.

**Comment by cseppan** [comment]
Fixed in SMOKE v5.1
