### ISSUE TITLE
Missing information about the SPDIST speed distribution profile option

### ISSUE THREAD

**Issue by bokhaeng** [CEMPD/SMOKE#87]
Looks like the information about the SPDIST input file for the optional speed distribution processing in Movesmrg is missing in the user's guide.

**Comment by bokhaeng** [comment]
Updated the Movesmrg figure with an optional SPDIST input file. Also, correct the typo of SPDPRO for Example 6.10 to SPDIST.

**Comment by bokhaeng** [comment]
https://github.com/CEMPD/smoke-manual/commit/838d983cfba5bf6c5fa0111e9d57d9f091ebe98d

**Comment by cseppan** [comment]
Included in SMOKE v5.1 User's Guide
