### ISSUE TITLE
Ambiguous definition of EFLAG variable in setoutdate

### ISSUE THREAD

**Issue by jlbeidler** [CEMPD/SMOKE#90]
Local logical variable EFLAG is not initialized with a default value in the setoudate.f subroutine. This could cause an incorrect exit at line 130 with certain compilers or compiler options.

**Comment by hnqtran** [comment]
Confirm that initialize EFLAG = .FALSE. in setoutdate.f solved the issue "'Inconsistent start time in input files" (which only occurred with gfortran compiler).

Change made to line 80:
`        LOGICAL       :: EFLAG = .FALSE.          ! true: an error has happened`
